application: <%= _.slugify(appId) %>
version: default
runtime: python27
threadsafe: yes
api_version: 1

handlers:
 - url: /(favicon\.ico|robots\.txt|)
   static_files: assets/\1
   upload: assets/.*
   expiration: "14d"