application: <%= _.slugify(appId) %>
version: default
runtime: python27
threadsafe: yes
api_version: 1

handlers:
# Admin console, see http://goo.gl/pQM9ll
 - url: /admin.*
   script: google.appengine.ext.admin.application
   login: admin